### ISSUE TITLE
Error on Scanning

### ISSUE THREAD

**Issue by Crocodile73** [AnesHamdani08/QuickBeat#1]
Windows 11 x64
add location for the library and press scan. Is it possible to add a location on a hard drive for library yet?

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at QuickBeat.Classes.MemoryManager._Closure$__._Lambda$__22-0(Metadata k)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at QuickBeat.Classes.MemoryManager.Clean()
   at QuickBeat.Classes.MemoryManager.PeriodicCleaner_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)

**Comment by AnesHamdani08** [comment]
Sorry for not replying soon, The github notification didn't work for some reason.
You can add a location on the hard drive:
 - Settings
   - Sources
     - Add
- As for the exception i'll investigate it.
Thank you for your feedback.

**Comment by AnesHamdani08** [comment]
### Fixed
Try the latest release (codename: [Elegance](https://github.com/AnesHamdani08/QuickBeat/releases/tag/1.2.0.2)) and see if your problem is fixed.
![image](https://github.com/AnesHamdani08/QuickBeat/assets/38377619/3a5131a7-4c00-4a1c-b9c8-d647c4bccde1)

**Comment by Crocodile73** [comment]
No error now. But it only finds 31 tracks. It said 709 will be added.

**Comment by AnesHamdani08** [comment]
> No error now. But it only finds 31 tracks. It said 709 will be added.

Make sure to rebuild your library the first time, and scan when you add songs
If the library is not adding songs then the file extensions (i.e ".mp3") may not be supported. make sure your files are in the supported file filter (Top Menu -> File -> Open).
If the problem is still occuring, please follow these instructions and send me the output.
 - Enable Debug Mode: Head to settings, Scroll to the bottom, You'll see Debug Mode: Enable , click on Enable
 - Open the developer console: press Ctrl + D
 - Make sure you selected the proper file paths in the library sources
 - Click rebuild, wait for the pop up to appear... Click Ok
 - If the app still not loading the whole library send me the Console output.
 Thank you for taking the time to submit your feedback ♥

**Comment by Crocodile73** [comment]
the developer window is not showing anything when i debug. The log has this, if it helps.

System.NullReferenceException: Object reference not set to an instance of an object.
   at QuickBeat.Library.Library._Closure$__._Lambda$__126-0(Metadata k)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at QuickBeat.Library.Library.EnsureMostPlayed(Metadata Item, Boolean SkipArtists)
   at QuickBeat.Library.WPF.Commands.LibraryRebuildCommand._Closure$__18-1._Lambda$__2()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at QuickBeat.Library.WPF.Commands.LibraryRebuildCommand._Closure$__18-0._Lambda$__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at QuickBeat.Library.WPF.Commands.LibraryRebuildCommand.VB$StateMachine_18_Execute.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AnesHamdani08** [comment]
@Crocodile73 
Thank you, the log definitely helped and the error is now fixed, i'll release a hotfix with the ready new features from the private build.
### Error Explanation
`Library.WPF.Commands.LibraryRebuildCommand` (Classes/Commands Ln.403) Iterates through all the files in your `Settings.APP_LIBRARY_PATHS` and Projects them to a `Player.Metadata` via `Player.Metadata.FromFile` (Classes.Player.Metadata Ln.444) when that function fails it return `Nothing` (Null reference). Then it passes those references (including the null ones in your case) to the library via the `Library.Add(item As Metadata, Optional UpdateMostPlayed As Boolean = True)` (Classes.Library Ln.833) which don't have a null protection (didn't add it because my library has only audio files with some image files that it didn't pick, so that issue never occured to me). After the rebuild is completed `Library.EnsureMostPlayed(Optional Item As Metadata = Nothing, Optional SkipArtists As Boolean = True)` (Classes.Library Ln.874) `OrderByDescending(Of Integer)(Function(k) k.PlayCount)` <-- Now this is the issue, because `k` is null for some references (`Library.Items`).
### The Fix
`OrderByDescending(Of Integer)(Function(k) k.PlayCount)` Is now `OrderByDescending(Of Integer)(Function(k) k?.PlayCount)` 
`Library.Add(item As Metadata, Optional UpdateMostPlayed As Boolean = True)` first line is now `If item Is Nothing Then Return`
`Library.WPF.Commands.LibraryRebuildCommand` Now has this `If file Is Nothing Then Continue For`

### Thank you for taking the time to provide feedback, the issue is now fixed and will be released shortly
### If you have any other feedback/issues feel free to open an issue.

Don't forget to close the issue if it's fixed.

**Comment by Crocodile73** [comment]
Fixed. many thanks
